### ISSUE TITLE
Fancy icon

### ISSUE THREAD

**Issue by rullzer** [nextcloud/twofactor_nextcloud_notification#16]

**Comment by rullzer** [comment]
@jancborchardt do you have an idea?

**Comment by jancborchardt** [comment]
I need some context, and the issue nor the readme don’t really provide that. ;D

The lock icon (`icon-password`) seems to be good in general for 2FA, no? https://docs.nextcloud.com/server/14/developer_manual/design/icons.html

**Comment by rullzer** [comment]
Yes it is. But if you have 4 providers and 3 have the password lock it is meaningless :wink: 

So what the app does when enabled is sending a notifiation. That you can approve for example on your phone.

**Comment by jancborchardt** [comment]
Let’s for now use the lock icon though. Yes it does make it a bit meaningless but it also groups the apps. (Also I don’t have any good ideas right now. :D And lock icon is a good start.)

**Comment by kowalski7cc** [comment]
What about `icon-notifications`?

**Comment by nickvergessen** [comment]
Maybe https://materialdesignicons.com/icon/bell-check ?

**Comment by nickvergessen** [comment]
> so it’s symmetric to what you have to look for

Not sure what to think about this, but you're the boss:
![grafik](https://github.com/user-attachments/assets/3fa84d65-d1ad-4b3f-87dd-23b2d2b6f81d)

**Comment by AndyScherzinger** [comment]
works for me 👍

**Comment by jancborchardt** [comment]
@nickvergessen yeah you are right, I was mostly thinking about which icon shows when you pick the "Nextcloud notification" entry after logging in. There it looks fitting – is it possible to use a different icon here?

Like a generic "Login" icon as: https://fonts.google.com/icons?icon.set=Material+Symbols&icon.size=24&icon.color=%235f6368&selected=Material+Symbols+Outlined:login:FILL@1;wght@400;GRAD@0;opsz@24&icon.query=login

**Comment by nickvergessen** [comment]
So Bell on the twofactor provider (when selecting during login and in personal settings where you enable it) and Login on the notification provider (my screenshot)?

**Comment by jancborchardt** [comment]
@nickvergessen yes, that sounds good! :)
