### ISSUE TITLE
2FA Not Working "Two-factor authentication is enforced but has not been configured"

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/twofactor_nextcloud_notification#398]
Allow the user to login for the first time after enabling this option to check the 2FA. Once i chcked it user cant login it would make sense to allow the user to first login to configure 2FA
![image](https://user-images.githubusercontent.com/59488153/93236875-f34d7d00-f744-11ea-9046-6cd0b5042123.png)
![image](https://user-images.githubusercontent.com/59488153/93236775-d6b14500-f744-11ea-8b20-a77f3e6b0a56.png)
![image](https://user-images.githubusercontent.com/59488153/93237299-8686b280-f745-11ea-895c-e2a042cc7f92.png)
![image](https://user-images.githubusercontent.com/59488153/93237340-969e9200-f745-11ea-8a60-a155b4e8cc27.png)

**Comment by Indirectelex** [comment]
yeah how can we fix that?

**Comment by bendschs** [comment]
same here

**Comment by nursoda** [comment]
To my knowledge the origin is a flaw in the overall 2FA logic (→server), not this app. The 2FA altogether lacks clear requirements posed upon apps implementing 2FA methods such as "Setup on first use" – which probably is the cause to what OP describes.

There are other correlating thoughts: Currently, it is not verified that 2FA Push is usable (at the time of setup). Other 2FA apps (such as TOTP and Email) require the user to prove that he can use the method prior to activating it.

Currently this app may be enabled only by users. An enhancement for certain company setups would be that the admin can roll out mobile devices with pre-configured NC app and enable the setting for those (or all) users.

**Comment by nickvergessen** [comment]
There is yet another flow with this app/2fa provider specifically which is: you can lock yourself out.

E.g. if you disconnect all your mobile clients and all browser cookies expire/are cleared. So enforcing this app as only 2fa solution is not really suitable and from my POV it should only be used in addition to other providers so users still have a fallback 2fa.

But again there is a flaw in the server logic as an app/provider can not signal something like this.
