### ISSUE TITLE
Feature request: IP address is personal data and should not be used in Login attempt message

### ISSUE THREAD

**Issue by mnheia** [nextcloud/twofactor_nextcloud_notification#732]
According to our current legislation in Slovenia (maybe other Europe countries as well), the IP address is considered personal data and should therefore be protected and its use limited.

I suggest a parameter, setting that would limit the output of the IP address in Notifier.php on line 110; it would therefore change from 'Login attempt from IP address {ip}' to 'Login attempt'.

**Comment by nickvergessen** [comment]
> should therefore be protected and its use limited.

It's use is very limited, the data is removed as soon as the login attempt was accepted or declined.
From my POV this is kind of necessary to have a minimum amount of security as a 2FA provider.

**Comment by mnheia** [comment]
Technically I think we both know that is not exactly true as that information is kept in logs. I agree with your statement though to some degree but it I don't think it should be displayed if not really necessary and from the point of authorizing the login I don't think it is really needed as most users won't even know what to do with this information other than cause privacy issues. If login is not authorized they should report and have IT check in more details anyway. 

If we just add a simple switching parameter to have this displayed or not based on legislation or decision of the administrator I think it would be a great feature.

**Comment by nickvergessen** [comment]
Well at the point you receive the IP address of an attacker, they managed to enter **your correct user password**.
I guess the GDPR of the attacker towards the victim is neglectable in this case.

> I think we both know that technically this is not exactly correct as information is kept in logs. 

Well we are only talking about this app here and for that the data retention I outlined about is true.

**Comment by nickvergessen** [comment]
Sure send a PR

**Comment by Gwindalmir** [comment]
Google's 2-factor tells you the IP and the city.
I'd much rather have the IP visible to me than not, as I can instantly tell at a glance if the login is legit, since I know my IP.

Since the IP being shown is supposed to be yours, since _you_ supposedly just performed a login, I don't see an issue.

The IP might be in logs, but how are regular users supposed to access that, ask an admin?
I guess an option is useful, but I wouldn't want to see it removed entirely.
